frj_calendar:
    resource: "@FrjCalendarBundle/Controller/"
    prefix:   annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "api/doc"
