<?php

namespace AppBundle\Entity;

/**
 * TicketsOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketsOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrderContainingTicketDetailAndRef($ref, TicketDetail $ticketDetail)
    {
        $queryBuilder = $this->createQueryBuilder('o')
            ->leftJoin('o.tickets','t')
            ->leftJoin('t.ticketDetails', 'td')
            ->where('td.id = :id')
            ->setParameter('id', $ticketDetail->getId())
            ->andWhere('o.ref = :ref')
            ->setParameter('ref', $ref);

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
