<?php

namespace AppBundle\Entity;

/**
 * TicketsOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketsOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrderContainingTicketDetailAndRef($ref, TicketDetail $ticketDetail)
    {
        $queryBuilder = $this->createQueryBuilder('o')
            ->leftJoin('o.tickets','t')
            ->leftJoin('t.ticketDetails', 'td')
            ->where('td.id = :id')
            ->setParameter('id', $ticketDetail->getId())
            ->andWhere('o.ref = :ref')
            ->setParameter('ref', $ref);

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }

    public function getMonthlyVisitors($year, $month)
    {
        $queryBuilder = $this->createQueryBuilder('o')
            ->leftJoin('o.tickets','t')
            ->leftJoin('t.ticketDetails', 'td')
            ->select(array('DAY(o.visitDate) as day', 'COUNT(td) as quantity'))
            ->where('MONTH(o.visitDate) = :month')
            ->setParameter('month', $month)
            ->andWhere('YEAR(o.visitDate) = :year')
            ->setParameter('year', $year)
            ->groupBy('day');

        return $queryBuilder->getQuery()->getArrayResult();
    }
}
