parameters:
    calendar_day_off: [7] # lundi: 1, Dimanche: 7

services:
#    frj_calendar.example:
#        class: Frj\CalendarBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    frj_calendar.calendar:
        class: Frj\CalendarBundle\Calendar\Calendar
        arguments: [@twig, %calendar_day_off%]